- platform: toon_smartmeter
  host: !secret toon_ip
  port: !secret toon_port
  scan_interval: 10
  resources:
    - gasused
    - gasusedcnt
    - elecusageflowpulse
    - elecusagecntpulse
#    - elecusageflowlow
#    - elecusagecntlow
#    - elecusageflowhigh
#    - elecusagecnthigh
#    - elecprodflowlow
#    - elecprodcntlow
#    - elecprodflowhigh
#    - elecprodcnthigh
#    - elecsolar
#    - elecsolarcnt
#    - heat
#    - waterflow
#    - waterquantity
