# Ledstrip van de action
substitutions:
  plug_name: plug-05
  plug_friendly_name: Monitor Links
  wifi_ssid: !secret wifi_name
  wifi_password: !secret wifi_code
  api_pw: !secret api_password
  ota_pw: !secret ota_password

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01_1m

# WiFi connection
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  domain: !secret domain
  fast_connect: true
  ap:
    ssid: ${plug_name}
    password: "qwe12345"

# Enable logging
logger:

# HOMEASSISTANT API
api:
  port: !secret esp_api_port
  encryption:
    key: !secret esp_encryption_key

# Enable over-the-air updates
ota:
  password: ${ota_pw}

# Enable Web server
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
    
# Configuratie

sensor:
  - platform: wifi_signal
    name: "${plug_friendly_name} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${plug_friendly_name} Uptime"

    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${plug_friendly_name} IP Address
    ssid:
      name: ${plug_friendly_name} Connected SSID
    bssid:
      name: ${plug_friendly_name} Connected BSSID

binary_sensor:
  - platform: status
    name: "$plug_friendly_name Status"
  - platform: gpio
    name: "$plug_friendly_name Button"
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    on_press:
      - switch.toggle: relay

output:
  - platform: esp8266_pwm
    id: led
    pin:
      number: GPIO4
      inverted: true

light:
  - platform: monochromatic
    id: status_led
    name: "$plug_friendly_name Led"
    output: led

switch:
  - platform: gpio
    id: relay
    pin: GPIO12
  - platform: template
    name: "$plug_friendly_name Relais"
    optimistic: true
    id: relay_and_light
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: status_led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: status_led
